#!/usr/bin/with-contenv bash
#shellcheck shell=bash

# Set readsb binary
DUMP978_BIN="/usr/local/bin/dump978-fa"

# Listen on 0.0.0.0:DUMP978_RAW_PORT for raw messages
DUMP978_CMD=("--raw-port" "0.0.0.0:30978")

# Listen on 0.0.0.0:DUMP978_JSON_PORT for json messages
DUMP978_CMD+=("--json-port" "0.0.0.0:30979")

DUMP978_CMD+=("--format" "CS8")

# Handle "--sdr"
if [[ -n "${DUMP978_DEVICE_TYPE:-rtlsdr}" ]]; then
    case "${DUMP978_DEVICE_TYPE:-rtlsdr}" in
        rtlsdr)
            if [[ -n "${DUMP978_RTLSDR_DEVICE}" ]]; then
                DUMP978_CMD+=("--sdr" "driver=rtlsdr,serial=${DUMP978_RTLSDR_DEVICE}")
            else
                DUMP978_CMD+=("--sdr" "driver=rtlsdr")
            fi
        ;;
        stratuxv3)
            if [[ -n "${DUMP978_STRATUXV3_DEVICE}" ]]; then
                DUMP978_CMD+=("--stratuxv3" "${DUMP978_STRATUXV3_DEVICE}")
            else
                >&2 echo "ERROR: Please set DUMP978_STRATUXV3_DEVICE!"
                sleep 60
                exit 1
            fi
        ;;
        *)
            >&2 echo "ERROR: Unsupported DUMP978_DEVICE_TYPE!"
            sleep 60
            exit 1
        ;;
    esac
fi

# Handle "--sdr-auto-gain"
if [[ -n "$DUMP978_SDR_AGC" ]]; then
    DUMP978_CMD+=("--sdr-auto-gain")
fi

# Handle "--sdr-gain"
if [[ -n "$DUMP978_SDR_GAIN" ]]; then
    DUMP978_CMD+=("--sdr-gain" "$DUMP978_SDR_GAIN")
fi

# Handle "--sdr-ppm"
if [[ -n "$DUMP978_SDR_PPM" ]]; then
    DUMP978_CMD+=("--sdr-ppm" "$DUMP978_SDR_PPM")
fi

# Handle "--json-stdout"
if [[ -n "$DUMP978_JSON_STDOUT" ]]; then
    DUMP978_CMD+=("--json-stdout")
fi

set -eo pipefail

# shellcheck disable=SC2016
"${DUMP978_BIN}" "${DUMP978_CMD[@]}" \
  2>&1 | stdbuf -o0 sed --unbuffered '/^$/d' | stdbuf -o0 awk '{print "[dump978] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

sleep 5
