#!/usr/bin/with-contenv bash
#shellcheck shell=bash

set -eo pipefail

sleep 5

socat -d -d -u "TCP:127.0.0.1:30978" STDOUT 2>&3 | \
uat2esnt 2>&4 | \
socat -d -d -u STDIN "TCP-LISTEN:37981,fork" \
2>&1 | stdbuf -o0 sed --unbuffered '/^$/d' | stdbuf -o0 awk '{print "[uat2esnt_socat_ext] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}' | \
3>&1 | stdbuf -o0 sed --unbuffered '/^$/d' | stdbuf -o0 awk '{print "[uat2esnt_socat_int] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}' | \
4>&1 | stdbuf -o0 sed --unbuffered '/^$/d' | stdbuf -o0 awk '{print "[uat2esnt] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}' | \
