#!/command/with-contenv bash
#shellcheck shell=bash

NOCOLOR='\033[0m'
LIGHTRED='\033[1;31m'

EXITCODE=0

# If troubleshooting:
if [[ -n "$DEBUG_LOGGING" ]]; then
    set -x
fi

# Check that if more than one rtlsdr, that we have a serial given
if [[ "$DUMP978_DEVICE_TYPE" == "rtlsdr" ]]; then
    # Prepare temp file
    biast_tempfile=$(mktemp)
    # Attempt to get devices, use random serial so it's very unlikely we claim an SDR used by someone else
    rtl_biast -d "$RANDOM$RANDOM" > "$biast_tempfile" 2>&1 || true
    # Get number of devices
    num_devices=$(sed -n 's/^Found\s\+\([0-9]\+\)\s\+device(s):\s*$/\1/p' "$biast_tempfile")
    # If we have more than one device, we need a serial number
    if [[ "$num_devices" -gt 1 ]]; then
        if [[ -z "$DUMP978_RTLSDR_DEVICE" ]]; then
            s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args echo -e "${NOCOLOR}ERROR: Multiple RTL-SDR devices present. Please set DUMP978_RTLSDR_DEVICE!${LIGHTRED}"
            EXITCODE=1
        fi
    fi
    rm "$biast_tempfile"
fi

# Ensure viewadsb exists:
if [[ ! -f /usr/local/bin/viewadsb ]]; then
    echo '#!/bin/bash' > /usr/local/bin/viewadsb
    echo '/usr/bin/readsb --interactive --net --net-only --net-connector 127.0.0.1,30978,uat_in $@' >> /usr/local/bin/viewadsb
    chmod a+x /usr/local/bin/viewadsb
fi

exit $EXITCODE
