#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2076,SC2154,SC2015

source /scripts/common

trap 'pkill -P $$ || true; exit 0' SIGTERM SIGINT SIGHUP SIGQUIT

# Autogain routine
#
# Relevant env variables:
#   DUMP978_GAIN or READSB_GAIN: set to "autogain" to enable autogain
#   DUMP978_AUTOGAIN_INITIAL_INTERVAL or READSB_AUTOGAIN_INITIAL_INTERVAL: time in seconds to run autogain during initial assessment period; 600 (=10 minutes)
#   DUMP978_AUTOGAIN_SUBSEQUENT_INTERVAL or READSB_AUTOGAIN_SUBSEQUENT_INTERVAL: time in seconds to run autogain during initial assessment period; 86400 (=1 day)
#   DUMP978_AUTOGAIN_INITIAL_TIMEPERIOD or READSB_AUTOGAIN_INITIAL_TIMEPERIOD: time in seconds that the initial gain assessment will last. Default 14400 (=4 hours)
# Command to restart autogain: docker exec -it dump978 /usr/local/bin/autogain978 reset

# make READSB_AUTOGAIN.... the same as DUMP978_AUTOGAIN with the latter as preferred parameter
READSB_AUTOGAIN_INITIAL_INTERVAL="${DUMP978_AUTOGAIN_INITIAL_INTERVAL:-${READSB_AUTOGAIN_INITIAL_INTERVAL:-600}}"
READSB_AUTOGAIN_SUBSEQUENT_INTERVAL="${DUMP978_AUTOGAIN_SUBSEQUENT_INTERVAL:-${READSB_AUTOGAIN_SUBSEQUENT_INTERVAL:-86400}}"
READSB_AUTOGAIN_INITIAL_TIMEPERIOD="${DUMP978_AUTOGAIN_INITIAL_TIMEPERIOD:-${READSB_AUTOGAIN_INITIAL_TIMEPERIOD:-21600}}"
READSB_AUTOGAIN_ADJUSTMENT_TIMEFRAME="${DUMP978_AUTOGAIN_ADJUSTMENT_TIMEFRAME:-${READSB_AUTOGAIN_ADJUSTMENT_TIMEFRAME:-0800-1800}}"
READSB_SDR_GAIN="${DUMP978_SDR_GAIN:-${READSB_SDR_GAIN}}"
READSB_AUTOGAIN_ADJUSTMENT_LIMITS="${DUMP978_AUTOGAIN_ADJUSTMENT_LIMITS:-${READSB_AUTOGAIN_ADJUSTMENT_LIMITS:-true}}"
READSB_AUTOGAIN_STRONGSIGNAL_LIMIT="${DUMP978_AUTOGAIN_STRONGSIGNAL_LIMIT:-${READSB_AUTOGAIN_STRONGSIGNAL_LIMIT:--3.5}}"

function collect_gain_values() {
    # reads RAW messages for $1 seconds and returns the percentage strong messages with 1 decimal precision
    # $2 is optionally the cut-off RSSI value for strong signals
    local total_msg=0
    local strong_msg=0
    local rssi
    local cutoff
    local errorcode=0
    local endtime

    if [[ -n "$2" ]]; then
        cutoff="$2"
        cutoff="$(bc -l <<< "scale=0; ${cutoff/#-} * 10 / 1")"
    else
        cutoff=30
    fi

    if [[ -z "$1" ]]; then
        s6wrap --quiet --prepend="$(basename "$0")" --timestamps --args echo "error - collect_gain_values function needs collection time as argument"
        return 99
    fi

    # collect the values and put them in an array
    chk_enabled "$(set -o|grep pipefail|awk '{print $2}')" && pipefailvalue="-o pipefail" || pipefailvalue="+o pipefail"
    set -o pipefail

    while read -r rssi; do
        (( total_msg++ ))
        (( rssi < cutoff )) && (( strong_msg++ )) || true
        # echo "rssi - $rssi total - $total_msg strong $strong_msg"
    done < <(timeout "$1" stdbuf -oL nc localhost 30978 | sed -n 's|^.*;rssi=-\([0-9]\+\)\.\([0-9]*\);.*$|\1\2|p' 2>/dev/null || errorcode="$?")
    set $pipefailvalue

    echo -n "$total_msg;$strong_msg;"
    if (( strong_msg * total_msg > 0 )); then
        bc -l <<< "scale=1; 100 * $strong_msg / $total_msg / 1"
    else
        echo "na"
    fi
}


if [[ "${READSB_SDR_GAIN,,}" != "autogain" ]]; then
    # Autogain is not enabled, so let's do nothing forever
    s6wrap --quiet --prepend="$(basename "$0")" --timestamps --args echo "Gain is set to ${READSB_SDR_GAIN}; autogain disabled."
    exec sleep infinity
fi

mkdir -p /var/globe_history/autogain

# Do special things if it's the first time AUTOGAIN is running
if [[ ! -f /var/globe_history/autogain/autogain_initialized ]]; then
    s6wrap --quiet --prepend="$(basename "$0")" --timestamps --args echo "Autogain initialization started. We'll collect data every $READSB_AUTOGAIN_INITIAL_INTERVAL secs for $(( READSB_AUTOGAIN_INITIAL_TIMEPERIOD / 60 )) minutes to do an initial gain assessment."

    # run autogain every $READSB_AUTOGAIN_INITIAL_INTERVAL secs for $READSB_AUTOGAIN_INITIAL_TIMEPERIOD secs
    for (( i=1; i<=$(( READSB_AUTOGAIN_INITIAL_TIMEPERIOD / READSB_AUTOGAIN_INITIAL_INTERVAL )); i++ ))
    do
        # check if adjustment time limits are enabled and if we are in the window; if we're not then sleep until we will be in the window
        if chk_enabled "$READSB_AUTOGAIN_ADJUSTMENT_LIMITS" && \
        (( $(date +%s) < $(date -d "${READSB_AUTOGAIN_ADJUSTMENT_TIMEFRAME%%-*} today" +%s) )); then
            # current time is before start of window; delay until window starts
            now_in_secs="$(date +%s)"
            resumetime_in_secs="$(date -d "${READSB_AUTOGAIN_ADJUSTMENT_TIMEFRAME%%-*} today" +%s)"
            s6wrap --quiet --prepend="$(basename "$0")" --timestamps --args echo "Too early: current time before ${READSB_AUTOGAIN_ADJUSTMENT_TIMEFRAME} adjustment time window. We will delay until $(date -d "${READSB_AUTOGAIN_ADJUSTMENT_TIMEFRAME%%-*}"), in $((resumetime_in_secs - now_in_secs))s"
            sleep $((resumetime_in_secs - now_in_secs)) & wait $!
         elif chk_enabled "$READSB_AUTOGAIN_ADJUSTMENT_LIMITS" && \
         (( $(date +%s) > $(date -d "${READSB_AUTOGAIN_ADJUSTMENT_TIMEFRAME##*-} today" +%s) )); then
            # current time is after close of window; delay until window starts tomorrow
            now_in_secs="$(date +%s)"
            resumetime_in_secs="$(date -d "${READSB_AUTOGAIN_ADJUSTMENT_TIMEFRAME%%-*} today" +%s)"
            if (( resumetime_in_secs < now_in_secs )); then resumetime_in_secs="$(date -d "${READSB_AUTOGAIN_ADJUSTMENT_TIMEFRAME%%-*} tomorrow" +%s)"; fi 
            s6wrap --quiet --prepend="$(basename "$0")" --timestamps --args echo "Too late: current time outside of ${READSB_AUTOGAIN_ADJUSTMENT_TIMEFRAME} adjustment time window. We will delay until $(date -d "${READSB_AUTOGAIN_ADJUSTMENT_TIMEFRAME%%-*} tomorrow"), in $((resumetime_in_secs - now_in_secs))s"
            sleep "$((resumetime_in_secs - now_in_secs))s" & wait $!
        fi

        # now collect data for $READSB_AUTOGAIN_INITIAL_INTERVAL seconds:
        endtime="$(( $(date +%s) + READSB_AUTOGAIN_INITIAL_INTERVAL ))"
        msg_stats="$(collect_gain_values "$READSB_AUTOGAIN_INITIAL_INTERVAL" "$READSB_AUTOGAIN_STRONGSIGNAL_LIMIT")"
        if (( $(date +%s) < endtime )); then
             # data collection exited early. Wait out the rest of the time and invalidate partial results
             sleep "$(( endtime - $(date +%s) ))"
             msg_stats="0;0;na"
        fi
        s6wrap --quiet --prepend="$(basename "$0")" --timestamps --args echo "Autogain initialization run $i of $(( READSB_AUTOGAIN_INITIAL_TIMEPERIOD / READSB_AUTOGAIN_INITIAL_INTERVAL ))..."
        if [[ msg_stats=="0;0;na" ]] || ! s6wrap --quiet --prepend="$(basename "$0")" --timestamps --args /usr/local/bin/autogain978 "$msg_stats"; then ((i--)) || true; fi
    done
    touch /var/globe_history/autogain/autogain_initialized
fi

s6wrap --quiet --prepend="$(basename "$0")" --timestamps --args echo "Autogain long-term maintenance started. We'll collect data and assess every $(( READSB_AUTOGAIN_SUBSEQUENT_INTERVAL / 60 )) minutes if gain needs to be adjusted."
while true
do
    endtime="$(( $(date +%s) + READSB_AUTOGAIN_SUBSEQUENT_INTERVAL ))"
    msg_stats="$(collect_gain_values "$READSB_AUTOGAIN_SUBSEQUENT_INTERVAL" "$READSB_AUTOGAIN_STRONGSIGNAL_LIMIT")"
    if (( $(date +%s) >= endtime )); then
         s6wrap --quiet --prepend="$(basename "$0")" --timestamps --args /usr/local/bin/autogain978 "$msg_stats"
    else
         # data collection exited early. Wait a bit and restart
         sleep 60 & wait !
    fi
done
