#!/command/with-contenv bash
#shellcheck shell=bash

# Ensure pid is created and has correct ownership
touch /run/lighttpd.pid
chown nobody /run/lighttpd.pid
mkdir -p /var/log/lighttpd
touch /var/log/lighttpd/error.log
truncate -s 0 /var/log/lighttpd/error.log
chown -R nobody /var/log/lighttpd


# Launch webapp unless disabled
if [[ -z "$DISABLE_WEBAPP" ]]; then
    s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args s6-setuidgid nobody /usr/sbin/lighttpd -tt -f /etc/lighttpd/lighttpd.conf || exit 0
    set -eo pipefail

    #shellcheck disable=SC2016
    s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args s6-setuidgid nobody /usr/sbin/lighttpd \
        -f /etc/lighttpd/lighttpd.conf \
        -D

# If webapp disabled, sleep forever
else
    sleep infinity
fi
