#!/command/with-contenv bash
#shellcheck shell=bash

while :
do
    # Make sure we're receiving messages from the SDR
    # get the number of messages received since process start:
    mkdir -p /run/stats
    if [[ -f /run/skyaware978/aircraft.json ]]; then
        read -r new_msg_count <<< "$(jq .messages /run/skyaware978/aircraft.json 2>/dev/null)"
    else
        new_msg_count="STARTING"
    fi
    # get the number of messages previously read, or 0 if there's no history:
    if [[ -f /run/stats/msgs_since_last_healthcheck ]]; then
        read -r old_msg_count < /run/stats/msgs_since_last_healthcheck
        secs_since_last_check="$(( $(date +%s) - $(stat -c '%Y' /run/stats/msgs_since_last_healthcheck) ))"
    else
        old_msg_count=0
        secs_since_last_check="$(( $(date +%s) - $(stat -c '%Y' /run/service/skyaware978) ))"    # use skyaware978 modify time as the creation time of the container
    fi

    if [[ "$new_msg_count" == "STARTING" ]]; then
        echo "[$(date)][STARTING] No messages have been received as the container is still starting"
        new_msg_count=0
    elif (( new_msg_count == old_msg_count )); then
        echo "[$(date)][UNHEALTHY] No messages received since last HealthCheck ($secs_since_last_check secs ago)"
    else
        echo "[$(date)][ERROR] This situation cannot occur; new_msg_count=$new_msg_count; old_msg_count=$old_msg_count"
    fi
    echo "$new_msg_count" > /run/stats/msgs_since_last_healthcheck

    sleep 15m
done
