#!/command/with-contenv bash
#shellcheck shell=bash

set -eo pipefail

sleep 2

# shellcheck disable=SC2016
s6wrap --quiet --timestamps --prepend="readsb" --args readsb --net-only --net --quiet --net-connector 127.0.0.1,30978,uat_in --net-ro-port 37981 --net-bo-port 37982
