#!/command/with-contenv bash
#shellcheck shell=bash

set -eo pipefail

s6wrap=(s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args)

sleep 2

READSB_BIN="readsb"
READSB_ARGS=("--net-only")
READSB_ARGS+=("--net")
READSB_ARGS+=("--quiet")
READSB_ARGS+=("--net-connector 127.0.0.1,30978,uat_in")
READSB_ARGS+=("--net-ro-port 37981")
READSB_ARGS+=("--net-bo-port 37982,30005")

"${s6wrap[@]}" echo "invoking: ${READSB_BIN} ${READSB_ARGS[*]}"

# shellcheck disable=SC2068
exec "${s6wrap[@]}" $READSB_BIN ${READSB_ARGS[@]}
