#!/command/with-contenv bash
#shellcheck shell=bash

set -eo pipefail

s6wrap=(s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args)

sleep 5

# patch skyaware978 to remove the "v=2?" from the URL
sed -i 's/v=2?//g' /usr/share/dump978-fa/html/index.html
sed -i 's/flightFeederCheck();//g' /usr/share/dump978-fa/html/script.js
sed -i 's/setStatsLink();//g' /usr/share/dump978-fa/html/script.js
sed -i 's/<button id="stats_page_button" class="stats_button">Go to My ADS-B Statistics Page<\/button>//g' /usr/share/dump978-fa/html/index.html

SKY_BIN="skyaware978"
SKY_ARGS=("--json-dir /run/skyaware978")
SKY_ARGS+=("--connect 127.0.0.1:30978")
SKY_ARGS+=("--reconnect-interval 30")
SKY_ARGS+=("--history-count 180")
SKY_ARGS+=("--history-interval 15")


if [[ -n "${LON}" ]] && [[ -n "${LAT}" ]]; then
    SKY_ARGS+=("--lat ${LAT}")
    SKY_ARGS+=("--lon ${LON}")
fi

"${s6wrap[@]}" echo "invoking: $SKY_BIN ${SKY_ARGS[*]}"
# shellcheck disable=SC2068
"${s6wrap[@]}" $SKY_BIN ${SKY_ARGS[@]}
