#!/command/with-contenv bash
#shellcheck shell=bash

set -eo pipefail

sleep 5

# patch skyaware978 to remove the "v=2?" from the URL
sed -i 's/v=2?//g' /usr/share/dump978-fa/html/index.html
sed -i 's/flightFeederCheck();//g' /usr/share/dump978-fa/html/script.js
sed -i 's/setStatsLink();//g' /usr/share/dump978-fa/html/script.js
sed -i 's/<button id="stats_page_button" class="stats_button">Go to My ADS-B Statistics Page<\/button>//g' /usr/share/dump978-fa/html/index.html


if [[ -n "${LON}" ]] && [[ -n "${LAT}" ]]; then
    optstr="--lat ${LAT} --lon ${LON}"
fi

# shellcheck disable=SC2016,SC2086
skyaware978 --json-dir /run/skyaware978 --connect 127.0.0.1:30978 --reconnect-interval 30 --history-count 180 --history-interval 15 ${optstr} \
2>&1 | stdbuf -o0 awk '{print "[skyware] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
