#!/command/with-contenv bash
#shellcheck shell=bash

set -eo pipefail

# Stats are only needed when telegraf is running
# They are no longer needed for autogain
# If the telegraf binary is not present, then do nothing:
if [[ ! -f /usr/bin/telegraf ]]; then
  sleep infinity
fi

sleep 5

# shellcheck disable=SC2016
exec s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args python3 -u /scripts/stats.py
