#!/command/with-contenv bash
#shellcheck shell=bash

# Connect VRS port to Telegraf port


set -eo pipefail

if [ -z "$INFLUXDB_SKIP_AIRCRAFT" ] && { [ -n "$INFLUXDBURL" ] || [ -n "$ENABLE_PROMETHEUS" ]; } then

  SOCAT_BIN="$(which socat)"
  SOCAT_CMD=(-ls)

  if [ "$VERBOSE_LOGGING" = "true" ]; then
    SOCAT_CMD+=("-d -d")
  fi

  SOCAT_CMD+=("TCP:localhost:30979")
  SOCAT_CMD+=("TCP:localhost:33979")

  # shellcheck disable=SC2016
  s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args "${SOCAT_BIN}" "${SOCAT_CMD[@]}" 

else
  sleep infinity
fi
