#!/command/with-contenv bash
#shellcheck shell=bash

set -eo pipefail

if [[ -n "$INFLUXDBURL" ]] || [ -n "$ENABLE_PROMETHEUS" ]; then

  #shellcheck disable=SC2016
  exec s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args telegraf \
    --config /etc/telegraf/telegraf.conf \
    --config-directory /etc/telegraf/telegraf.d \

else
  sleep infinity
fi
