#!/command/with-contenv bash
#shellcheck shell=bash

set -eo pipefail

# If the telegraf binary is not present, then do nothing:
if [[ ! -f /usr/bin/telegraf ]]; then
  sleep infinity
fi

if [[ -n "$INFLUXDBURL" ]] || [ -n "$ENABLE_PROMETHEUS" ]; then

  #shellcheck disable=SC2016
  exec s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args telegraf \
    --config /etc/telegraf/telegraf.conf \
    --config-directory /etc/telegraf/telegraf.d \
    | grep -v "Error in plugin"
else
  sleep infinity
fi
