#!/usr/bin/with-contenv bash
#shellcheck shell=bash

set -eo pipefail

sleep 5

# shellcheck disable=SC2016
python3 -u /scripts/stats.py \
2>&1 | stdbuf -o0 sed --unbuffered '/^$/d' | stdbuf -o0 awk '{print "[stats] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
