#!/usr/bin/with-contenv bash
#shellcheck shell=bash

# Connect VRS port to Telegraf port


set -eo pipefail

if [[ -n "$INFLUXDBURL" ]]; then

  SOCAT_BIN="$(which socat)"
  SOCAT_CMD=(-ls)

  if [ "$VERBOSE_LOGGING" = "true" ]; then
    SOCAT_CMD+=("-d -d")
  fi

  SOCAT_CMD+=("TCP:localhost:30979")
  SOCAT_CMD+=("TCP:localhost:33979")

  # shellcheck disable=SC2016
  "${SOCAT_BIN}" "${SOCAT_CMD[@]}" \
    2>&1 | stdbuf -o0 awk '{print "[telegraf_socat] " $0}'

else
  sleep 86400
fi
