#!/usr/bin/with-contenv bash
#shellcheck shell=bash

set -eo pipefail

sleep 5

if [[ -n "${LON}" ]] && [[ -n "${LAT}" ]]; then
    optstr="--lat ${LAT} --lon ${LON}"
fi

# shellcheck disable=SC2016,SC2086
skyaware978 --json-dir /run/uat2json --connect 127.0.0.1:30978 --reconnect-interval 30 --history-count 180 --history-interval 15 ${optstr} \
2>&1 | stdbuf -o0 awk '{print "[skyware] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
