#!/usr/bin/with-contenv bash
#shellcheck shell=bash

set -eo pipefail

sleep 5

[[ -n "${LON}" ]] && [[ -n "${LAT}" ]] && optstr="--rec-pos ${LAT},${LON}"

# shellcheck disable=SC2086
socat -u "TCP:127.0.0.1:30978" STDOUT | \
    uat2json ${optstr} /run/uat2json 2>&1 | \
    stdbuf -o0 sed --unbuffered '/^$/d' | \
    stdbuf -o0 awk '{print "[uat2json] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
