#!/usr/bin/with-contenv bash
#shellcheck shell=bash

set -eo pipefail

sleep 5

# shellcheck disable=SC2016
socat -u "TCP:127.0.0.1:30978" STDOUT | \
uat2json /run/uat2json \
2>&1 | stdbuf -o0 sed --unbuffered '/^$/d' | stdbuf -o0 awk '{print "[uat2json] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
